In [1]:
# Importing the necessary libraries
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split ,  GridSearchCV
from sklearn.metrics import accuracy_score, classification_report
import pickle

In [2]:
# Importing the csv file
data = pd.read_csv("C://Users//lenovo 2020//Employee_performance.csv")

In [3]:
data.head()

,EmpNumber,Age,Gender,EducationBackground,MaritalStatus,EmpDepartment,EmpJobRole,BusinessTravelFrequency,DistanceFromHome,EmpEducationLevel,...,EmpRelationshipSatisfaction,TotalWorkExperienceInYears,TrainingTimesLastYear,EmpWorkLifeBalance,ExperienceYearsAtThisCompany,ExperienceYearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition,PerformanceRating
0,E1001000,32,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,10,3,...,4,10,2,2,10,7,0,8,No,3
1,E1001006,47,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,14,4,...,4,20,2,3,7,7,1,7,No,3
2,E1001007,40,Male,Life Sciences,Married,Sales,Sales Executive,Travel_Frequently,5,4,...,3,20,2,3,18,13,1,12,No,4
3,E1001009,41,Male,Human Resources,Divorced,Human Resources,Manager,Travel_Rarely,10,4,...,2,23,2,2,21,6,12,6,No,3
4,E1001010,60,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,16,4,...,4,10,1,3,2,2,2,2,No,3

In [4]:
for col in data.columns:
    unique_vals = data[col].unique().tolist()
    print(f"{col} = {unique_vals}")

EmpNumber = ['E1001000', 'E1001006', 'E1001007', 'E1001009', 'E1001010', 'E1001011', 'E1001016', 'E1001019', 'E1001020', 'E1001021', 'E1001022', 'E1001024', 'E1001025', 'E1001027', 'E1001030', 'E1001035', 'E1001038', 'E1001040', 'E1001041', 'E1001042', 'E1001044', 'E1001047', 'E1001049', 'E1001050', 'E1001053', 'E1001054', 'E1001058', 'E1001059', 'E1001061', 'E1001062', 'E1001063', 'E1001064', 'E1001067', 'E1001069', 'E1001070', 'E1001071', 'E1001074', 'E1001075', 'E1001077', 'E1001078', 'E1001080', 'E1001081', 'E1001082', 'E1001083', 'E1001085', 'E1001086', 'E1001090', 'E1001091', 'E1001093', 'E1001094', 'E1001095', 'E1001097', 'E1001098', 'E1001101', 'E1001102', 'E1001104', 'E1001105', 'E1001106', 'E1001107', 'E1001110', 'E1001111', 'E1001112', 'E1001114', 'E1001115', 'E1001118', 'E1001120', 'E1001121', 'E1001122', 'E1001123', 'E1001124', 'E1001126', 'E1001128', 'E1001129', 'E1001130', 'E1001132', 'E1001134', 'E1001135', 'E1001140', 'E1001142', 'E1001143', 'E1001146', 'E1001147', 'E1001150', 'E1001152', 'E1001153', 'E1001156', 'E1001157', 'E1001159', 'E1001160', 'E1001165', 'E1001166', 'E1001167', 'E1001171', 'E1001173', 'E1001175', 'E1001178', 'E1001179', 'E1001180', 'E1001181', 'E1001182', 'E1001183', 'E1001187', 'E1001188', 'E1001189', 'E1001191', 'E1001196', 'E1001200', 'E1001201', 'E1001202', 'E1001203', 'E1001204', 'E1001208', 'E1001210', 'E1001211', 'E1001212', 'E1001214', 'E1001217', 'E1001218', 'E1001219', 'E1001220', 'E1001223', 'E1001225', 'E1001227', 'E1001228', 'E1001229', 'E1001230', 'E1001235', 'E1001236', 'E1001237', 'E1001238', 'E1001239', 'E1001245', 'E1001248', 'E1001250', 'E1001252', 'E1001253', 'E1001254', 'E1001259', 'E1001260', 'E1001262', 'E1001263', 'E1001264', 'E1001265', 'E1001268', 'E1001269', 'E1001270', 'E1001272', 'E1001273', 'E1001274', 'E1001275', 'E1001276', 'E1001277', 'E1001280', 'E1001281', 'E1001282', 'E1001283', 'E1001284', 'E1001288', 'E1001289', 'E1001290', 'E1001291', 'E1001292', 'E1001293', 'E1001296', 'E1001297', 'E1001300', 'E1001302', 'E1001303', 'E1001304', 'E1001305', 'E1001306', 'E1001307', 'E1001308', 'E1001310', 'E1001312', 'E1001313', 'E1001314', 'E1001315', 'E1001316', 'E1001317', 'E1001318', 'E1001321', 'E1001322', 'E1001323', 'E1001324', 'E1001325', 'E1001326', 'E1001327', 'E1001330', 'E1001331', 'E1001334', 'E1001338', 'E1001339', 'E1001340', 'E1001344', 'E1001346', 'E1001348', 'E1001349', 'E1001351', 'E1001352', 'E1001354', 'E1001355', 'E1001357', 'E1001358', 'E1001360', 'E1001361', 'E1001362', 'E1001366', 'E1001370', 'E1001372', 'E1001374', 'E1001376', 'E1001379', 'E1001381', 'E1001384', 'E1001385', 'E1001387', 'E1001389', 'E1001391', 'E1001392', 'E1001393', 'E1001394', 'E1001395', 'E1001396', 'E1001397', 'E1001398', 'E1001399', 'E1001402', 'E1001403', 'E1001405', 'E1001406', 'E1001410', 'E1001411', 'E1001413', 'E1001414', 'E1001415', 'E1001416', 'E1001418', 'E1001421', 'E1001426', 'E1001428', 'E1001432', 'E1001434', 'E1001435', 'E1001436', 'E1001438', 'E1001439', 'E1001440', 'E1001441', 'E1001442', 'E1001443', 'E1001444', 'E1001445', 'E1001449', 'E1001451', 'E1001453', 'E1001455', 'E1001457', 'E1001458', 'E1001460', 'E1001462', 'E1001463', 'E1001466', 'E1001468', 'E1001469', 'E1001470', 'E1001471', 'E1001473', 'E1001474', 'E1001478', 'E1001479', 'E1001481', 'E1001482', 'E1001484', 'E1001485', 'E1001489', 'E1001490', 'E1001493', 'E1001495', 'E1001496', 'E1001497', 'E1001498', 'E1001499', 'E1001503', 'E1001509', 'E1001512', 'E1001513', 'E1001515', 'E1001516', 'E1001518', 'E1001520', 'E1001522', 'E1001523', 'E1001524', 'E1001526', 'E1001528', 'E1001529', 'E1001533', 'E1001534', 'E1001535', 'E1001536', 'E1001538', 'E1001541', 'E1001542', 'E1001545', 'E1001548', 'E1001553', 'E1001555', 'E1001556', 'E1001557', 'E1001558', 'E1001559', 'E1001560', 'E1001561', 'E1001563', 'E1001564', 'E1001566', 'E1001567', 'E1001569', 'E1001570', 'E1001571', 'E1001572', 'E1001574', 'E1001575', 'E1001576', 'E1001577', 'E1001579', 'E1001581', 'E1001582', 'E1001584', 'E1001585', 'E1001586', 'E1001587', 'E1001590', 'E1001592', 'E1001593', 'E1001595', 'E1001596', 'E1001597', 'E1001602', 'E1001607', 'E1001614', 'E1001616', 'E1001618', 'E1001622', 'E1001627', 'E1001628', 'E1001630', 'E1001633', 'E1001634', 'E1001636', 'E1001638', 'E1001639', 'E1001640', 'E1001641', 'E1001642', 'E1001645', 'E1001646', 'E1001647', 'E1001649', 'E1001650', 'E1001651', 'E1001652', 'E1001653', 'E1001655', 'E1001657', 'E1001660', 'E1001661', 'E1001665', 'E1001668', 'E1001669', 'E1001670', 'E1001673', 'E1001674', 'E1001675', 'E1001677', 'E1001679', 'E1001680', 'E1001681', 'E1001683', 'E1001685', 'E1001686', 'E1001689', 'E1001690', 'E1001693', 'E1001697', 'E1001698', 'E1001700', 'E1001701', 'E1001703', 'E1001705', 'E1001706', 'E1001708', 'E1001709', 'E1001711', 'E1001712', 'E1001713', 'E1001716', 'E1001717', 'E1001718', 'E1001719', 'E1001723', 'E1001725', 'E1001726', 'E1001727', 'E1001731', 'E1001736', 'E1001737', 'E1001738', 'E1001739', 'E1001743', 'E1001745', 'E1001746', 'E1001749', 'E1001751', 'E1001752', 'E1001753', 'E1001755', 'E1001756', 'E1001757', 'E1001758', 'E1001759', 'E1001760', 'E1001761', 'E1001762', 'E1001763', 'E1001764', 'E1001767', 'E1001770', 'E1001773', 'E1001774', 'E1001775', 'E1001779', 'E1001780', 'E1001781', 'E1001782', 'E1001784', 'E1001785', 'E1001787', 'E1001791', 'E1001792', 'E1001793', 'E1001794', 'E1001798', 'E1001800', 'E1001805', 'E1001807', 'E1001811', 'E1001812', 'E1001813', 'E1001817', 'E1001820', 'E1001821', 'E1001822', 'E1001823', 'E1001824', 'E1001825', 'E1001826', 'E1001827', 'E1001828', 'E1001829', 'E1001830', 'E1001831', 'E1001832', 'E1001834', 'E1001835', 'E1001838', 'E1001840', 'E1001841', 'E1001846', 'E1001847', 'E1001850', 'E1001851', 'E1001854', 'E1001855', 'E1001856', 'E1001858', 'E1001860', 'E1001863', 'E1001864', 'E1001865', 'E1001866', 'E1001868', 'E1001869', 'E1001870', 'E1001874', 'E1001875', 'E1001877', 'E1001882', 'E1001883', 'E1001884', 'E1001885', 'E1001886', 'E1001887', 'E1001889', 'E1001890', 'E1001891', 'E1001892', 'E1001893', 'E1001895', 'E1001897', 'E1001899', 'E1001900', 'E1001901', 'E1001902', 'E1001903', 'E1001905', 'E1001908', 'E1001909', 'E1001911', 'E1001916', 'E1001918', 'E1001919', 'E1001920', 'E1001923', 'E1001924', 'E1001925', 'E1001926', 'E1001931', 'E1001932', 'E1001933', 'E1001934', 'E1001935', 'E1001936', 'E1001937', 'E1001939', 'E1001940', 'E1001942', 'E1001943', 'E1001944', 'E1001945', 'E1001947', 'E1001948', 'E1001949', 'E1001951', 'E1001952', 'E1001958', 'E1001959', 'E1001960', 'E1001961', 'E1001962', 'E1001965', 'E1001967', 'E1001969', 'E1001970', 'E1001971', 'E1001972', 'E1001974', 'E1001975', 'E1001978', 'E1001979', 'E1001981', 'E1001984', 'E1001987', 'E1001988', 'E1001990', 'E1001996', 'E1001997', 'E1001999', 'E1002000', 'E1002002', 'E1002003', 'E1002005', 'E1002007', 'E1002009', 'E1002010', 'E1002011', 'E1002012', 'E1002014', 'E1002015', 'E1002017', 'E1002018', 'E1002022', 'E1002023', 'E1002024', 'E1002025', 'E1002027', 'E1002029', 'E1002030', 'E1002031', 'E1002032', 'E1002033', 'E1002034', 'E1002035', 'E1002036', 'E1002038', 'E1002042', 'E1002044', 'E1002045', 'E1002048', 'E1002049', 'E1002050', 'E1002052', 'E1002053', 'E1002056', 'E1002057', 'E1002058', 'E1002060', 'E1002061', 'E1002062', 'E1002067', 'E1002068', 'E1002070', 'E1002072', 'E1002076', 'E1002079', 'E1002080', 'E1002082', 'E1002083', 'E1002085', 'E1002090', 'E1002091', 'E1002092', 'E1002093', 'E1002101', 'E1002102', 'E1002104', 'E1002105', 'E1002107', 'E1002108', 'E1002111', 'E1002113', 'E1002114', 'E1002115', 'E1002117', 'E1002120', 'E1002123', 'E1002125', 'E1002127', 'E1002128', 'E1002130', 'E1002131', 'E1002132', 'E1002134', 'E1002135', 'E1002136', 'E1002137', 'E1002138', 'E1002140', 'E1002141', 'E1002142', 'E1002143', 'E1002145', 'E1002146', 'E1002151', 'E1002153', 'E1002154', 'E1002156', 'E1002158', 'E1002160', 'E1002161', 'E1002163', 'E1002164', 'E1002166', 'E1002168', 'E1002170', 'E1002171', 'E1002176', 'E1002178', 'E1002181', 'E1002183', 'E1002185', 'E1002186', 'E1002187', 'E1002189', 'E1002190', 'E1002193', 'E1002194', 'E1002196', 'E1002200', 'E1002202', 'E1002205', 'E1002207', 'E1002209', 'E1002210', 'E1002212', 'E1002213', 'E1002215', 'E1002216', 'E1002217', 'E1002218', 'E1002219', 'E1002221', 'E1002222', 'E1002223', 'E1002225', 'E1002226', 'E1002227', 'E1002228', 'E1002229', 'E1002230', 'E1002233', 'E1002238', 'E1002239', 'E1002240', 'E1002243', 'E1002244', 'E1002245', 'E1002246', 'E1002247', 'E1002248', 'E1002249', 'E1002250', 'E1002251', 'E1002252', 'E1002253', 'E1002254', 'E1002257', 'E1002258', 'E1002259', 'E1002260', 'E1002263', 'E1002264', 'E1002265', 'E1002267', 'E1002270', 'E1002271', 'E1002273', 'E1002274', 'E1002276', 'E1002277', 'E1002278', 'E1002281', 'E1002285', 'E1002286', 'E1002287', 'E1002288', 'E1002290', 'E1002291', 'E1002292', 'E1002293', 'E1002295', 'E1002296', 'E1002297', 'E1002298', 'E1002299', 'E1002301', 'E1002302', 'E1002303', 'E1002304', 'E1002305', 'E1002310', 'E1002312', 'E1002313', 'E1002314', 'E1002315', 'E1002316', 'E1002318', 'E1002319', 'E1002322', 'E1002323', 'E1002326', 'E1002327', 'E1002329', 'E1002330', 'E1002331', 'E1002332', 'E1002333', 'E1002334', 'E1002335', 'E1002338', 'E1002340', 'E1002342', 'E1002343', 'E1002346', 'E100279', 'E100285', 'E100286', 'E100288', 'E100289', 'E100291', 'E100292', 'E100294', 'E100296', 'E100297', 'E100298', 'E100300', 'E100301', 'E100302', 'E100304', 'E100306', 'E100309', 'E100310', 'E100311', 'E100313', 'E100314', 'E100316', 'E100317', 'E100318', 'E100323', 'E100324', 'E100325', 'E100327', 'E100329', 'E100330', 'E100331', 'E100332', 'E100333', 'E100334', 'E100335', 'E100338', 'E100339', 'E100340', 'E100341', 'E100342', 'E100343', 'E100346', 'E100348', 'E100350', 'E100351', 'E100352', 'E100353', 'E100354', 'E100355', 'E100356', 'E100357', 'E100358', 'E100359', 'E100361', 'E100363', 'E100364', 'E100366', 'E100368', 'E100372', 'E100373', 'E100374', 'E100375', 'E100376', 'E100378', 'E100381', 'E100382', 'E100383', 'E100384', 'E100385', 'E100388', 'E100391', 'E100395', 'E100396', 'E100397', 'E100398', 'E100399', 'E100402', 'E100403', 'E100406', 'E100407', 'E100409', 'E100410', 'E100411', 'E100412', 'E100416', 'E100417', 'E100419', 'E100420', 'E100421', 'E100422', 'E100425', 'E100426', 'E100428', 'E100429', 'E100430', 'E100431', 'E100433', 'E100436', 'E100438', 'E100440', 'E100441', 'E100442', 'E100443', 'E100445', 'E100447', 'E100448', 'E100449', 'E100452', 'E100453', 'E100454', 'E100455', 'E100456', 'E100457', 'E100461', 'E100462', 'E100470', 'E100471', 'E100472', 'E100475', 'E100478', 'E100479', 'E100482', 'E100483', 'E100484', 'E100485', 'E100486', 'E100492', 'E100493', 'E100494', 'E100496', 'E100499', 'E100501', 'E100502', 'E100504', 'E100505', 'E100506', 'E100508', 'E100509', 'E100511', 'E100513', 'E100516', 'E100517', 'E100518', 'E100519', 'E100520', 'E100521', 'E100522', 'E100523', 'E100525', 'E100526', 'E100527', 'E100528', 'E100530', 'E100531', 'E100534', 'E100536', 'E100537', 'E100538', 'E100539', 'E100540', 'E100542', 'E100545', 'E100547', 'E100548', 'E100549', 'E100551', 'E100552', 'E100553', 'E100555', 'E100559', 'E100560', 'E100561', 'E100562', 'E100564', 'E100565', 'E100569', 'E100571', 'E100574', 'E100576', 'E100577', 'E100578', 'E100580', 'E100581', 'E100582', 'E100584', 'E100586', 'E100589', 'E100590', 'E100592', 'E100593', 'E100594', 'E100597', 'E100599', 'E100601', 'E100603', 'E100605', 'E100606', 'E100607', 'E100609', 'E100610', 'E100611', 'E100612', 'E100615', 'E100616', 'E100617', 'E100618', 'E100619', 'E100620', 'E100621', 'E100625', 'E100627', 'E100628', 'E100629', 'E100630', 'E100631', 'E100637', 'E100639', 'E100640', 'E100641', 'E100642', 'E100644', 'E100645', 'E100647', 'E100650', 'E100652', 'E100655', 'E100656', 'E100657', 'E100658', 'E100659', 'E100660', 'E100662', 'E100663', 'E100664', 'E100665', 'E100668', 'E100669', 'E100670', 'E100671', 'E100672', 'E100673', 'E100674', 'E100677', 'E100679', 'E100681', 'E100682', 'E100683', 'E100684', 'E100685', 'E100686', 'E100688', 'E100689', 'E100690', 'E100695', 'E100697', 'E100698', 'E100699', 'E100701', 'E100702', 'E100703', 'E100704', 'E100706', 'E100707', 'E100708', 'E100709', 'E100712', 'E100714', 'E100715', 'E100716', 'E100717', 'E100719', 'E100722', 'E100723', 'E100724', 'E100725', 'E100727', 'E100729', 'E100730', 'E100731', 'E100732', 'E100734', 'E100736', 'E100738', 'E100739', 'E100740', 'E100741', 'E100742', 'E100744', 'E100745', 'E100746', 'E100747', 'E100748', 'E100752', 'E100754', 'E100756', 'E100757', 'E100759', 'E100760', 'E100761', 'E100762', 'E100766', 'E100770', 'E100771', 'E100772', 'E100773', 'E100774', 'E100775', 'E100776', 'E100777', 'E100778', 'E100779', 'E100780', 'E100783', 'E100786', 'E100788', 'E100789', 'E100791', 'E100792', 'E100793', 'E100794', 'E100796', 'E100798', 'E100799', 'E100800', 'E100802', 'E100803', 'E100805', 'E100807', 'E100808', 'E100809', 'E100811', 'E100812', 'E100814', 'E100816', 'E100821', 'E100822', 'E100824', 'E100825', 'E100826', 'E100827', 'E100828', 'E100832', 'E100833', 'E100834', 'E100836', 'E100838', 'E100840', 'E100842', 'E100843', 'E100844', 'E100845', 'E100846', 'E100847', 'E100852', 'E100853', 'E100855', 'E100856', 'E100857', 'E100858', 'E100859', 'E100860', 'E100862', 'E100863', 'E100864', 'E100865', 'E100868', 'E100869', 'E100870', 'E100871', 'E100873', 'E100875', 'E100877', 'E100878', 'E100880', 'E100882', 'E100883', 'E100884', 'E100890', 'E100891', 'E100892', 'E100893', 'E100894', 'E100898', 'E100899', 'E100900', 'E100901', 'E100902', 'E100903', 'E100908', 'E100912', 'E100913', 'E100916', 'E100917', 'E100919', 'E100921', 'E100922', 'E100923', 'E100925', 'E100927', 'E100928', 'E100931', 'E100933', 'E100934', 'E100937', 'E100939', 'E100940', 'E100941', 'E100942', 'E100943', 'E100944', 'E100945', 'E100947', 'E100949', 'E100953', 'E100957', 'E100958', 'E100961', 'E100964', 'E100967', 'E100968', 'E100969', 'E100976', 'E100977', 'E100979', 'E100980', 'E100983', 'E100985', 'E100987', 'E100988', 'E100990', 'E100992', 'E100993', 'E100994', 'E100995', 'E100998']
Age = [32, 47, 40, 41, 60, 27, 50, 28, 36, 38, 44, 30, 29, 42, 34, 39, 56, 53, 35, 52, 33, 25, 45, 23, 26, 54, 37, 24, 49, 55, 43, 51, 22, 31, 58, 20, 21, 48, 19, 18, 59, 46, 57]
Gender = ['Male', 'Female']
EducationBackground = ['Marketing', 'Life Sciences', 'Human Resources', 'Medical', 'Other', 'Technical Degree']
MaritalStatus = ['Single', 'Married', 'Divorced']
EmpDepartment = ['Sales', 'Human Resources', 'Development', 'Data Science', 'Research & Development', 'Finance']
EmpJobRole = ['Sales Executive', 'Manager', 'Developer', 'Sales Representative', 'Human Resources', 'Senior Developer', 'Data Scientist', 'Senior Manager R&D', 'Laboratory Technician', 'Manufacturing Director', 'Research Scientist', 'Healthcare Representative', 'Research Director', 'Manager R&D', 'Finance Manager', 'Technical Architect', 'Business Analyst', 'Technical Lead', 'Delivery Manager']
BusinessTravelFrequency = ['Travel_Rarely', 'Travel_Frequently', 'Non-Travel']
DistanceFromHome = [10, 14, 5, 16, 8, 1, 24, 3, 27, 19, 9, 2, 7, 6, 26, 11, 23, 13, 29, 12, 4, 25, 21, 18, 20, 17, 22, 28, 15]
EmpEducationLevel = [3, 4, 2, 5, 1]
EmpEnvironmentSatisfaction = [4, 2, 1, 3]
EmpHourlyRate = [55, 42, 48, 73, 84, 32, 54, 67, 63, 81, 49, 99, 57, 96, 44, 86, 83, 61, 80, 31, 46, 79, 77, 60, 76, 41, 71, 66, 38, 72, 95, 82, 75, 93, 64, 36, 69, 33, 35, 40, 43, 51, 52, 98, 45, 37, 94, 59, 88, 50, 65, 53, 56, 78, 74, 91, 62, 87, 68, 34, 70, 100, 92, 39, 97, 47, 90, 85, 30, 58, 89]
EmpJobInvolvement = [3, 2, 1, 4]
EmpJobLevel = [2, 3, 5, 1, 4]
EmpJobSatisfaction = [4, 1, 2, 3]
NumCompaniesWorked = [1, 2, 5, 3, 8, 7, 9, 4, 6, 0]
OverTime = ['No', 'Yes']
EmpLastSalaryHikePercent = [12, 21, 15, 14, 13, 23, 11, 20, 19, 17, 18, 22, 16, 24, 25]
EmpRelationshipSatisfaction = [4, 3, 2, 1]
TotalWorkExperienceInYears = [10, 20, 23, 9, 4, 28, 1, 7, 12, 30, 5, 2, 19, 16, 34, 6, 8, 11, 17, 3, 14, 26, 13, 22, 0, 29, 18, 35, 33, 31, 24, 15, 32, 21, 27, 25, 36, 37, 38, 40]
TrainingTimesLastYear = [2, 1, 4, 5, 6, 3, 0]
EmpWorkLifeBalance = [2, 3, 4, 1]
ExperienceYearsAtThisCompany = [10, 7, 18, 21, 2, 9, 8, 1, 5, 22, 4, 0, 34, 6, 15, 3, 13, 26, 20, 12, 31, 16, 11, 14, 17, 19, 32, 24, 33, 29, 25, 36, 30, 23, 27, 37, 40]
ExperienceYearsInCurrentRole = [7, 13, 6, 2, 0, 1, 3, 8, 9, 5, 4, 14, 12, 10, 16, 11, 15, 17, 18]
YearsSinceLastPromotion = [0, 1, 12, 2, 3, 11, 7, 4, 5, 14, 8, 15, 6, 10, 13, 9]
YearsWithCurrManager = [8, 7, 12, 6, 2, 5, 0, 4, 13, 3, 1, 16, 9, 17, 11, 10, 14, 15]
Attrition = ['No', 'Yes']
PerformanceRating = [3, 4, 2]

In [5]:
data.drop(['EmpNumber'],inplace=True,axis=1)

In [6]:
# Here we have selected only the important columns
y = data.Attrition
#X = data.iloc[:,0:-1]  All predictors were selected it resulted in dropping of accuracy.
X = data.iloc[:,[9,16,20,21,22,23,24]] # Taking only variables with correlation coeffecient greater than 0.1
X.head()

,EmpEnvironmentSatisfaction,EmpLastSalaryHikePercent,EmpWorkLifeBalance,ExperienceYearsAtThisCompany,ExperienceYearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,4,12,2,10,7,0,8
1,4,12,3,7,7,1,7
2,4,21,3,18,13,1,12
3,2,15,2,21,6,12,6
4,1,14,3,2,2,2,2

In [7]:
# Splitting into train and test for calculating the accuracy
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=10)

In [8]:
X_train.shape

(840, 7)

In [9]:
X_test.shape

(360, 7)

In [10]:
# Standardization technique is used
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
# Training the model
from sklearn.ensemble import RandomForestClassifier

classifier_rfg=RandomForestClassifier(random_state=33,n_estimators=23)
parameters=[{'min_samples_split':[2,3,4,5],'criterion':['gini','entropy'],'min_samples_leaf':[1,2,3]}]

model_gridrf=GridSearchCV(estimator=classifier_rfg, param_grid=parameters, scoring='accuracy',cv=10)
model_gridrf.fit(X_train,y_train)

GridSearchCV(cv=10,
             estimator=RandomForestClassifier(n_estimators=23, random_state=33),
             param_grid=[{'criterion': ['gini', 'entropy'],
                          'min_samples_leaf': [1, 2, 3],
                          'min_samples_split': [2, 3, 4, 5]}],
             scoring='accuracy')

In [12]:
model_gridrf.best_params_

{'criterion': 'gini', 'min_samples_leaf': 2, 'min_samples_split': 2}

In [13]:
y_predict_rf = model_gridrf.predict(X_test)

In [14]:
# Finding accuracy, precision, recall and confusion matrix
print(accuracy_score(y_test,y_predict_rf))
print(classification_report(y_test,y_predict_rf))

0.8472222222222222
              precision    recall  f1-score   support

          No       0.86      0.98      0.92       306
         Yes       0.44      0.07      0.13        54

    accuracy                           0.85       360
   macro avg       0.65      0.53      0.52       360
weighted avg       0.80      0.85      0.80       360

In [15]:
# Save model for performance prediction
emp_attrition_filename = r'C:\\Users\\lenovo 2020\\OneDrive\\Desktop\\Khushi Chadha- BCA min-major project\\models\\emp_attrition.pkl'
with open(emp_attrition_filename, 'wb') as f:
    pickle.dump(model_gridrf, f)

# Save the scaler used for standardization
scaler_filename = r'C:\\Users\\lenovo 2020\\OneDrive\\Desktop\\Khushi Chadha- BCA min-major project\\models\\emp_att_scaler.pkl'
with open(scaler_filename, 'wb') as f:
    pickle.dump(sc, f)

print("Performance model and scaler saved successfully.")

Performance model and scaler saved successfully.