In [2]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
import pickle

In [3]:
df = pd.read_csv("C://Users//lenovo 2020//marketing_campaign.csv", delimiter=';')

In [4]:
df.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,2012-09-04,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,2014-03-08,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,2013-08-21,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,2014-02-10,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,2014-01-19,94,173,...,5,0,0,0,0,0,0,3,11,0

In [5]:
# Droping nulls
df = df.dropna()

In [6]:
# Are there any duplicates?
df.duplicated().sum()

0

In [7]:
df['Total_Accepted'] = df['AcceptedCmp1'] + df['AcceptedCmp2'] + df['AcceptedCmp3']
+ df['AcceptedCmp4'] + df['AcceptedCmp5']

0       0
1       0
2       0
3       0
4       0
       ..
2235    0
2236    0
2237    1
2238    0
2239    0
Length: 2216, dtype: int64

In [8]:
df['Total_spent'] = df[['MntWines', 'MntFruits','MntMeatProducts',
'MntFishProducts', 'MntSweetProducts','MntGoldProds']].sum(axis = 1)

In [9]:
X = df[['Total_Accepted', 'Total_spent', 'NumCatalogPurchases']]
y= df['Response']

In [10]:
X.head()

   Total_Accepted  Total_spent  NumCatalogPurchases
0               0         1617                   10
1               0           27                    1
2               0          776                    2
3               0           53                    0
4               0          422                    3

In [11]:
for col in X.columns:
    unique_vals = X[col].unique().tolist()
    print(f"{col} = {unique_vals}")

Total_Accepted = [0, 1, 2, 3]
Total_spent = [1617, 27, 776, 53, 422, 716, 590, 169, 46, 49, 61, 1102, 310, 1315, 96, 317, 1782, 133, 316, 1730, 972, 544, 444, 75, 257, 131, 1672, 30, 318, 120, 302, 1196, 65, 913, 81, 67, 902, 1395, 22, 31, 984, 122, 55, 1319, 507, 1693, 72, 606, 1957, 1093, 29, 518, 1438, 612, 884, 1076, 34, 11, 1274, 653, 1562, 1253, 863, 661, 13, 1890, 2209, 18, 692, 165, 16, 79, 778, 56, 151, 372, 1366, 194, 32, 43, 45, 63, 978, 410, 1169, 1120, 1097, 187, 910, 145, 850, 969, 1820, 608, 730, 551, 114, 1724, 577, 33, 660, 80, 1135, 559, 1923, 90, 463, 632, 725, 279, 1482, 106, 38, 2077, 1053, 1385, 871, 312, 877, 68, 211, 127, 459, 460, 429, 89, 1021, 1381, 306, 162, 1231, 1706, 121, 1293, 1608, 88, 421, 259, 1117, 36, 57, 148, 93, 119, 1835, 1318, 10, 191, 1033, 66, 50, 39, 1581, 1282, 91, 315, 834, 1600, 1270, 263, 535, 1295, 1150, 1240, 35, 293, 1804, 241, 1101, 264, 541, 1198, 482, 17, 1615, 285, 1047, 714, 185, 1245, 189, 576, 1103, 1753, 433, 1588, 19, 69, 23, 605, 2088, 1009, 26, 1627, 1690, 1390, 2126, 1531, 64, 1112, 210, 1148, 322, 44, 845, 275, 25, 1495, 184, 981, 1635, 60, 231, 48, 99, 770, 957, 818, 925, 908, 102, 461, 37, 70, 930, 859, 1478, 390, 52, 137, 1919, 1374, 100, 825, 916, 62, 728, 273, 1213, 107, 1157, 546, 1508, 235, 401, 28, 680, 20, 1307, 630, 1283, 160, 71, 1161, 59, 946, 1442, 1674, 1853, 1538, 139, 1182, 940, 42, 1190, 835, 1443, 1029, 1188, 1277, 1670, 900, 425, 2153, 636, 494, 693, 1348, 51, 1932, 990, 254, 1371, 73, 1377, 324, 41, 492, 1005, 1173, 1738, 222, 1127, 209, 787, 1598, 186, 47, 1040, 163, 343, 446, 272, 490, 915, 1485, 369, 1073, 1242, 78, 1378, 1474, 751, 1435, 2119, 1795, 1008, 1688, 684, 1082, 1068, 733, 467, 156, 14, 192, 1379, 428, 868, 1001, 431, 971, 348, 2059, 265, 270, 1289, 893, 926, 135, 1288, 1743, 15, 542, 890, 1388, 906, 973, 530, 506, 54, 296, 266, 747, 895, 735, 205, 2092, 309, 1722, 682, 663, 1816, 976, 746, 1445, 1210, 945, 216, 943, 347, 1924, 397, 2089, 138, 777, 1902, 1651, 358, 1727, 1291, 442, 1895, 411, 521, 1168, 493, 260, 319, 1062, 232, 76, 201, 406, 662, 134, 21, 526, 240, 795, 1772, 1572, 889, 331, 1065, 177, 1230, 182, 227, 215, 143, 1867, 611, 473, 2086, 382, 819, 1151, 594, 129, 213, 1193, 268, 882, 373, 326, 404, 95, 939, 1237, 1825, 103, 1586, 963, 1587, 1375, 393, 1477, 1179, 486, 2252, 1092, 599, 2008, 1174, 365, 6, 1095, 223, 597, 1064, 74, 198, 1048, 574, 670, 1241, 172, 664, 928, 2074, 1146, 689, 2114, 1717, 1346, 1044, 126, 1004, 734, 614, 1453, 1621, 637, 948, 903, 112, 596, 233, 1511, 1152, 1185, 965, 869, 1947, 1380, 1027, 836, 480, 284, 1472, 1677, 1335, 334, 1338, 1099, 97, 109, 1574, 960, 1215, 1497, 449, 1757, 1440, 1006, 1226, 1171, 92, 564, 1427, 86, 833, 242, 1869, 1364, 183, 450, 758, 1507, 654, 1158, 1525, 24, 813, 629, 377, 1612, 729, 767, 1071, 1580, 573, 170, 1167, 1526, 458, 405, 726, 860, 495, 570, 769, 1808, 1576, 1616, 1043, 385, 1633, 761, 290, 1066, 2009, 1345, 764, 195, 368, 1180, 727, 40, 292, 341, 995, 989, 595, 128, 2018, 1281, 83, 353, 1003, 1139, 797, 1638, 84, 203, 858, 409, 282, 1423, 1449, 199, 178, 1990, 350, 1650, 1228, 1761, 1149, 2052, 1416, 1113, 125, 966, 1829, 779, 811, 1187, 2302, 1250, 683, 305, 77, 171, 475, 694, 361, 1079, 578, 149, 1778, 491, 1564, 1910, 94, 1085, 1415, 1908, 2486, 1789, 805, 108, 1493, 936, 528, 1901, 724, 58, 297, 488, 2194, 116, 1363, 236, 1314, 702, 1211, 1461, 1968, 1091, 313, 655, 704, 1123, 497, 691, 12, 2440, 968, 278, 938, 1178, 1155, 1826, 766, 2116, 1298, 396, 967, 357, 1401, 2087, 523, 1192, 1958, 424, 756, 937, 1862, 367, 443, 267, 1323, 562, 1156, 1104, 426, 635, 757, 332, 330, 384, 1956, 2013, 1313, 1060, 1459, 1833, 237, 515, 1020, 1370, 1026, 301, 499, 218, 1711, 438, 225, 470, 2525, 504, 1232, 155, 1812, 988, 1072, 174, 1084, 685, 363, 545, 2047, 140, 152, 101, 789, 87, 130, 1631, 899, 711, 351, 8, 1536, 992, 1529, 418, 587, 641, 2279, 1779, 793, 1383, 999, 246, 610, 1286, 362, 2130, 1229, 485, 434, 496, 2346, 794, 802, 1736, 1305, 832, 1501, 1189, 1194, 656, 1540, 311, 820, 274, 448, 1643, 1121, 1678, 1400, 1424, 844, 299, 320, 441, 85, 800, 1483, 1258, 1555, 861, 634, 1918, 586, 447, 1143, 415, 251, 371, 1899, 325, 417, 289, 188, 354, 146, 454, 1428, 817, 1131, 294, 1930, 2283, 879, 1244, 690, 1134, 529, 180, 2349, 534, 556, 1471, 175, 1078, 1115, 217, 1034, 1159, 380, 736, 269, 2524, 1045, 436, 1396, 642, 907, 1658, 854, 1662, 5, 1234, 1513, 271, 904, 1086, 1128, 964, 167, 677, 1106, 792, 407, 1269, 841, 633, 1019, 147, 1798, 1105, 974, 221, 1682, 892, 339, 1410, 2352, 1334, 1141, 710, 561, 601, 244, 638, 894, 1750, 823, 117, 335, 1792, 772, 1603, 2091, 1533, 82, 304, 1754, 815, 688, 708, 1695, 1080, 153, 1220, 745, 2157, 1597, 1067, 2034, 1991, 1686, 252, 1327, 1456, 563, 1504, 1125, 1376, 1382, 2231, 622, 224, 1165, 144, 917, 253, 502, 255, 398, 1921, 416, 1797, 914, 1502, 763, 1331, 525, 9, 953, 388, 173, 929, 219, 1052, 159, 1024, 1042, 395, 557, 1365, 1217, 581, 2257, 1049, 1515, 1039, 1596, 1828, 1702, 2069, 732, 801, 1685, 277, 1028, 1263, 1490, 1815, 909, 1676, 1735, 1191, 1280, 1336, 749, 414, 901, 455, 775, 1512, 1089, 1272, 816, 157, 1130, 1544, 1012, 1766, 161, 1734, 1138, 1429, 982, 359, 193, 2211, 2217, 1691, 809, 484, 413, 115, 1464, 283, 1870, 1941, 839, 1655, 1175, 874, 1260, 392, 1109, 639, 1665, 1392, 158, 1575, 1208, 527, 932, 1088, 993, 1680, 98, 519, 715, 1455, 602, 176, 961, 1518, 400, 1216, 1367, 2053, 1264, 2006, 615, 437, 1013, 1038, 1573, 123, 132, 1822, 1931, 258, 798, 300, 731, 1701, 1565, 1479, 568, 1199, 873, 2043, 1893, 575, 1016, 1566, 1644, 1528, 141, 500, 849, 1147, 1623, 679, 468, 1341, 843]
NumCatalogPurchases = [10, 1, 2, 0, 3, 4, 6, 28, 9, 5, 8, 7, 11, 22]

In [12]:
y.head()

0    1
1    0
2    0
3    0
4    0
Name: Response, dtype: int64

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [14]:
sc = StandardScaler()
X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.transform(X_test)

In [15]:
svm_model = SVC(kernel='rbf', random_state=42)
svm_model.fit(X_train_scaled, y_train)

SVC(random_state=42)

In [16]:
y_pred = svm_model.predict(X_test_scaled)

In [17]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 86.71%

In [18]:
# Step 3: Predict and evaluate
y_pred = svm_model.predict(X_test_scaled)
accuracy = accuracy_score(y_test, y_pred)
print("SVM Accuracy:", round(accuracy * 100, 2), "%")

SVM Accuracy: 86.71 %

In [19]:
# Step 4: Save the SVM model
svm_model_filename = r'C:\\Users\\lenovo 2020\\OneDrive\\Desktop\\Khushi Chadha- BCA min-major project\\models\\market_campaign.pkl'
with open(svm_model_filename, 'wb') as f:
    pickle.dump(svm_model, f)

# Step 5: Save the scaler
scaler_filename = r'C:\\Users\\lenovo 2020\\OneDrive\\Desktop\\Khushi Chadha- BCA min-major project\\models\\campaign_scaler.pkl'
with open(scaler_filename, 'wb') as f:
    pickle.dump(sc, f)

print("SVM performance model and scaler saved successfully.")

SVM performance model and scaler saved successfully.